package org.trustify.operator.cdrs.v2alpha1.keycloak.service;

import io.fabric8.kubernetes.api.model.Service;
import io.javaoperatorsdk.operator.api.reconciler.Context;
import io.javaoperatorsdk.operator.api.reconciler.dependent.DependentResource;
import io.javaoperatorsdk.operator.processing.dependent.workflow.Condition;
import org.trustify.operator.Constants;
import org.trustify.operator.cdrs.v2alpha1.Trustify;
import org.trustify.operator.services.ClusterService;

public class KeycloakTlsServiceReadyPostCondition implements Condition<Service, Trustify> {

    @Override
    public boolean isMet(DependentResource<Service, Trustify> resource, Trustify cr, Context<Trustify> context) {
        KeycloakTlsServiceActivationCondition activationCondition = new KeycloakTlsServiceActivationCondition();
        if (activationCondition.isMet(resource, cr, context)) {
            final var clusterService = context.managedDependentResourceContext().getMandatory(Constants.CLUSTER_SERVICE, ClusterService.class);
            return clusterService.getCluster().getAutoGeneratedKeycloakTlsSecret(cr).isPresent();
        }
        return true;
    }

}
