name: CI

on:
  push:
    branches:
      - main
      - "release-*"
  pull_request:
    branches:
      - main
      - "release-*"

jobs:
#  build-operator-bundle:
#    runs-on: ubuntu-latest
#    env:
#      IMG: ttl.sh/trustify-operator-${{ github.sha }}:2h
#      BUNDLE_IMG: ttl.sh/trustify-operator-bundle-${{ github.sha }}:2h
#    steps:
#      - uses: actions/checkout@v4
#      - name: Create operator
#        run: DOCKERFILE=Dockerfile.jvm make docker-build docker-push
#      - name: Create operator-bundle
#        run: make bundle-build bundle-push
  run-ci:
#    needs: build-operator-bundle
    uses: carlosthe19916/trustify-ci/.github/workflows/global-ci.yml@main
    with:
      operator_bundle: quay.io/konveyor/tackle2-operator-bundle:latest